import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Flame, Search } from "lucide-react";
import { StoryCard } from "@/components/story-card";
import { stories } from "@/lib/stories";
import fireplace from "@/assets/hot-fireplace.jpg";

export const Route=createFileRoute("/dang-hot")({head:()=>({meta:[{title:"Đang hot — Truyền Thuyết Đô Thị"},{name:"description",content:"Những lời đồn đang được đọc và nhắc đến nhiều nhất tuần này."},{property:"og:title",content:"Chuyện gì đang hot?"},{property:"og:description",content:"Ghé bảng bần xem những lời đồn đang nóng."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:TrendingPage});
function TrendingPage(){const [query,setQuery]=useState("");const ordered=[...stories].sort((a,b)=>b.views-a.views).filter((s)=>s.title.toLowerCase().includes(query.toLowerCase()));return <div className="trending-page section-pad"><div className="site-container"><header className="trending-banner"><Flame/><div><span className="tape-label">Bảng tin tuần này</span><h1 className="mt-5 font-display text-6xl sm:text-7xl">Chuyện gì đang hot?</h1><p className="mt-3">Mấy lời đồn này đang được chuyền tay nhanh lắm.</p></div><Flame/></header><div className="mx-auto mt-10 max-w-xl search-field"><Search/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Tìm lời đồn…"/></div><div className="mt-8 flex flex-wrap justify-center gap-2">{["Nhật Bản","Chuyện lạ","Tuần này","Đọc nhiều"].map(x=><span className="filter-chip" key={x}>{x}</span>)}</div><div className="corkboard mt-10"><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-3">{ordered.slice(0,6).map((story,index)=><StoryCard story={story} index={index} cork key={story.slug}/>)}</div><div className="fireplace-note"><img src={fireplace} alt="Chú ma ngạc nhiên trong lò sưởi hoạt hình" width={1024} height={1024} loading="lazy"/><span>Nóng theo nghĩa dễ thương!</span></div></div></div></div>}
