/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CongDongRouteImport } from './routes/cong-dong'
import { Route as DangHotRouteImport } from './routes/dang-hot'
import { Route as KhamPhaNgauNhienRouteImport } from './routes/kham-pha-ngau-nhien'
import { Route as TruyenThuyetRouteImport } from './routes/truyen-thuyet'
import { Route as VeChungToiRouteImport } from './routes/ve-chung-toi'
import { Route as CongDongIndexRouteImport } from './routes/cong-dong.index'
import { Route as CongDongIdRouteImport } from './routes/cong-dong.$id'
import { Route as CongDongDangTruyenRouteImport } from './routes/cong-dong.dang-truyen'
import { Route as TruyenThuyetIndexRouteImport } from './routes/truyen-thuyet.index'
import { Route as TruyenThuyetSlugRouteImport } from './routes/truyen-thuyet.$slug'
import { Route as TruyenThuyetChuDeTopicRouteImport } from './routes/truyen-thuyet.chu-de.$topic'
import { Route as TruyenThuyetQuocGiaCountryRouteImport } from './routes/truyen-thuyet.quoc-gia.$country'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CongDongRoute = CongDongRouteImport.update({
  id: '/cong-dong',
  path: '/cong-dong',
  getParentRoute: () => rootRouteImport,
} as any)
const DangHotRoute = DangHotRouteImport.update({
  id: '/dang-hot',
  path: '/dang-hot',
  getParentRoute: () => rootRouteImport,
} as any)
const KhamPhaNgauNhienRoute = KhamPhaNgauNhienRouteImport.update({
  id: '/kham-pha-ngau-nhien',
  path: '/kham-pha-ngau-nhien',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenThuyetRoute = TruyenThuyetRouteImport.update({
  id: '/truyen-thuyet',
  path: '/truyen-thuyet',
  getParentRoute: () => rootRouteImport,
} as any)
const VeChungToiRoute = VeChungToiRouteImport.update({
  id: '/ve-chung-toi',
  path: '/ve-chung-toi',
  getParentRoute: () => rootRouteImport,
} as any)
const CongDongIndexRoute = CongDongIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CongDongRoute,
} as any)
const CongDongIdRoute = CongDongIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CongDongRoute,
} as any)
const CongDongDangTruyenRoute = CongDongDangTruyenRouteImport.update({
  id: '/dang-truyen',
  path: '/dang-truyen',
  getParentRoute: () => CongDongRoute,
} as any)
const TruyenThuyetIndexRoute = TruyenThuyetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TruyenThuyetRoute,
} as any)
const TruyenThuyetSlugRoute = TruyenThuyetSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TruyenThuyetRoute,
} as any)
const TruyenThuyetChuDeTopicRoute = TruyenThuyetChuDeTopicRouteImport.update({
  id: '/chu-de/$topic',
  path: '/chu-de/$topic',
  getParentRoute: () => TruyenThuyetRoute,
} as any)
const TruyenThuyetQuocGiaCountryRoute =
  TruyenThuyetQuocGiaCountryRouteImport.update({
    id: '/quoc-gia/$country',
    path: '/quoc-gia/$country',
    getParentRoute: () => TruyenThuyetRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cong-dong': typeof CongDongRouteWithChildren
  '/dang-hot': typeof DangHotRoute
  '/kham-pha-ngau-nhien': typeof KhamPhaNgauNhienRoute
  '/truyen-thuyet': typeof TruyenThuyetRouteWithChildren
  '/ve-chung-toi': typeof VeChungToiRoute
  '/cong-dong/$id': typeof CongDongIdRoute
  '/cong-dong/dang-truyen': typeof CongDongDangTruyenRoute
  '/truyen-thuyet/$slug': typeof TruyenThuyetSlugRoute
  '/cong-dong/': typeof CongDongIndexRoute
  '/truyen-thuyet/': typeof TruyenThuyetIndexRoute
  '/truyen-thuyet/chu-de/$topic': typeof TruyenThuyetChuDeTopicRoute
  '/truyen-thuyet/quoc-gia/$country': typeof TruyenThuyetQuocGiaCountryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dang-hot': typeof DangHotRoute
  '/kham-pha-ngau-nhien': typeof KhamPhaNgauNhienRoute
  '/ve-chung-toi': typeof VeChungToiRoute
  '/cong-dong/$id': typeof CongDongIdRoute
  '/cong-dong/dang-truyen': typeof CongDongDangTruyenRoute
  '/truyen-thuyet/$slug': typeof TruyenThuyetSlugRoute
  '/cong-dong': typeof CongDongIndexRoute
  '/truyen-thuyet': typeof TruyenThuyetIndexRoute
  '/truyen-thuyet/chu-de/$topic': typeof TruyenThuyetChuDeTopicRoute
  '/truyen-thuyet/quoc-gia/$country': typeof TruyenThuyetQuocGiaCountryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cong-dong': typeof CongDongRouteWithChildren
  '/dang-hot': typeof DangHotRoute
  '/kham-pha-ngau-nhien': typeof KhamPhaNgauNhienRoute
  '/truyen-thuyet': typeof TruyenThuyetRouteWithChildren
  '/ve-chung-toi': typeof VeChungToiRoute
  '/cong-dong/$id': typeof CongDongIdRoute
  '/cong-dong/dang-truyen': typeof CongDongDangTruyenRoute
  '/truyen-thuyet/$slug': typeof TruyenThuyetSlugRoute
  '/cong-dong/': typeof CongDongIndexRoute
  '/truyen-thuyet/': typeof TruyenThuyetIndexRoute
  '/truyen-thuyet/chu-de/$topic': typeof TruyenThuyetChuDeTopicRoute
  '/truyen-thuyet/quoc-gia/$country': typeof TruyenThuyetQuocGiaCountryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cong-dong'
    | '/dang-hot'
    | '/kham-pha-ngau-nhien'
    | '/truyen-thuyet'
    | '/ve-chung-toi'
    | '/cong-dong/$id'
    | '/cong-dong/dang-truyen'
    | '/truyen-thuyet/$slug'
    | '/cong-dong/'
    | '/truyen-thuyet/'
    | '/truyen-thuyet/chu-de/$topic'
    | '/truyen-thuyet/quoc-gia/$country'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dang-hot'
    | '/kham-pha-ngau-nhien'
    | '/ve-chung-toi'
    | '/cong-dong/$id'
    | '/cong-dong/dang-truyen'
    | '/truyen-thuyet/$slug'
    | '/cong-dong'
    | '/truyen-thuyet'
    | '/truyen-thuyet/chu-de/$topic'
    | '/truyen-thuyet/quoc-gia/$country'
  id:
    | '__root__'
    | '/'
    | '/cong-dong'
    | '/dang-hot'
    | '/kham-pha-ngau-nhien'
    | '/truyen-thuyet'
    | '/ve-chung-toi'
    | '/cong-dong/$id'
    | '/cong-dong/dang-truyen'
    | '/truyen-thuyet/$slug'
    | '/cong-dong/'
    | '/truyen-thuyet/'
    | '/truyen-thuyet/chu-de/$topic'
    | '/truyen-thuyet/quoc-gia/$country'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CongDongRoute: typeof CongDongRouteWithChildren
  DangHotRoute: typeof DangHotRoute
  KhamPhaNgauNhienRoute: typeof KhamPhaNgauNhienRoute
  TruyenThuyetRoute: typeof TruyenThuyetRouteWithChildren
  VeChungToiRoute: typeof VeChungToiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-dong': {
      id: '/cong-dong'
      path: '/cong-dong'
      fullPath: '/cong-dong'
      preLoaderRoute: typeof CongDongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-hot': {
      id: '/dang-hot'
      path: '/dang-hot'
      fullPath: '/dang-hot'
      preLoaderRoute: typeof DangHotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kham-pha-ngau-nhien': {
      id: '/kham-pha-ngau-nhien'
      path: '/kham-pha-ngau-nhien'
      fullPath: '/kham-pha-ngau-nhien'
      preLoaderRoute: typeof KhamPhaNgauNhienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen-thuyet': {
      id: '/truyen-thuyet'
      path: '/truyen-thuyet'
      fullPath: '/truyen-thuyet'
      preLoaderRoute: typeof TruyenThuyetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ve-chung-toi': {
      id: '/ve-chung-toi'
      path: '/ve-chung-toi'
      fullPath: '/ve-chung-toi'
      preLoaderRoute: typeof VeChungToiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-dong/': {
      id: '/cong-dong/'
      path: '/'
      fullPath: '/cong-dong/'
      preLoaderRoute: typeof CongDongIndexRouteImport
      parentRoute: typeof CongDongRoute
    }
    '/cong-dong/$id': {
      id: '/cong-dong/$id'
      path: '/$id'
      fullPath: '/cong-dong/$id'
      preLoaderRoute: typeof CongDongIdRouteImport
      parentRoute: typeof CongDongRoute
    }
    '/cong-dong/dang-truyen': {
      id: '/cong-dong/dang-truyen'
      path: '/dang-truyen'
      fullPath: '/cong-dong/dang-truyen'
      preLoaderRoute: typeof CongDongDangTruyenRouteImport
      parentRoute: typeof CongDongRoute
    }
    '/truyen-thuyet/': {
      id: '/truyen-thuyet/'
      path: '/'
      fullPath: '/truyen-thuyet/'
      preLoaderRoute: typeof TruyenThuyetIndexRouteImport
      parentRoute: typeof TruyenThuyetRoute
    }
    '/truyen-thuyet/$slug': {
      id: '/truyen-thuyet/$slug'
      path: '/$slug'
      fullPath: '/truyen-thuyet/$slug'
      preLoaderRoute: typeof TruyenThuyetSlugRouteImport
      parentRoute: typeof TruyenThuyetRoute
    }
    '/truyen-thuyet/chu-de/$topic': {
      id: '/truyen-thuyet/chu-de/$topic'
      path: '/chu-de/$topic'
      fullPath: '/truyen-thuyet/chu-de/$topic'
      preLoaderRoute: typeof TruyenThuyetChuDeTopicRouteImport
      parentRoute: typeof TruyenThuyetRoute
    }
    '/truyen-thuyet/quoc-gia/$country': {
      id: '/truyen-thuyet/quoc-gia/$country'
      path: '/quoc-gia/$country'
      fullPath: '/truyen-thuyet/quoc-gia/$country'
      preLoaderRoute: typeof TruyenThuyetQuocGiaCountryRouteImport
      parentRoute: typeof TruyenThuyetRoute
    }
  }
}

interface CongDongRouteChildren {
  CongDongIdRoute: typeof CongDongIdRoute
  CongDongDangTruyenRoute: typeof CongDongDangTruyenRoute
  CongDongIndexRoute: typeof CongDongIndexRoute
}

const CongDongRouteChildren: CongDongRouteChildren = {
  CongDongIdRoute: CongDongIdRoute,
  CongDongDangTruyenRoute: CongDongDangTruyenRoute,
  CongDongIndexRoute: CongDongIndexRoute,
}

const CongDongRouteWithChildren = CongDongRoute._addFileChildren(
  CongDongRouteChildren,
)

interface TruyenThuyetRouteChildren {
  TruyenThuyetSlugRoute: typeof TruyenThuyetSlugRoute
  TruyenThuyetIndexRoute: typeof TruyenThuyetIndexRoute
  TruyenThuyetChuDeTopicRoute: typeof TruyenThuyetChuDeTopicRoute
  TruyenThuyetQuocGiaCountryRoute: typeof TruyenThuyetQuocGiaCountryRoute
}

const TruyenThuyetRouteChildren: TruyenThuyetRouteChildren = {
  TruyenThuyetSlugRoute: TruyenThuyetSlugRoute,
  TruyenThuyetIndexRoute: TruyenThuyetIndexRoute,
  TruyenThuyetChuDeTopicRoute: TruyenThuyetChuDeTopicRoute,
  TruyenThuyetQuocGiaCountryRoute: TruyenThuyetQuocGiaCountryRoute,
}

const TruyenThuyetRouteWithChildren = TruyenThuyetRoute._addFileChildren(
  TruyenThuyetRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CongDongRoute: CongDongRouteWithChildren,
  DangHotRoute: DangHotRoute,
  KhamPhaNgauNhienRoute: KhamPhaNgauNhienRoute,
  TruyenThuyetRoute: TruyenThuyetRouteWithChildren,
  VeChungToiRoute: VeChungToiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
