/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DangHotRouteImport } from './routes/dang-hot'
import { Route as KhamPhaNgauNhienRouteImport } from './routes/kham-pha-ngau-nhien'
import { Route as TruyenThuyetRouteImport } from './routes/truyen-thuyet'
import { Route as VeChungToiRouteImport } from './routes/ve-chung-toi'
import { Route as TruyenThuyetIndexRouteImport } from './routes/truyen-thuyet.index'
import { Route as TruyenThuyetSlugRouteImport } from './routes/truyen-thuyet.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangHotRoute = DangHotRouteImport.update({
  id: '/dang-hot',
  path: '/dang-hot',
  getParentRoute: () => rootRouteImport,
} as any)
const KhamPhaNgauNhienRoute = KhamPhaNgauNhienRouteImport.update({
  id: '/kham-pha-ngau-nhien',
  path: '/kham-pha-ngau-nhien',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenThuyetRoute = TruyenThuyetRouteImport.update({
  id: '/truyen-thuyet',
  path: '/truyen-thuyet',
  getParentRoute: () => rootRouteImport,
} as any)
const VeChungToiRoute = VeChungToiRouteImport.update({
  id: '/ve-chung-toi',
  path: '/ve-chung-toi',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenThuyetIndexRoute = TruyenThuyetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TruyenThuyetRoute,
} as any)
const TruyenThuyetSlugRoute = TruyenThuyetSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TruyenThuyetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dang-hot': typeof DangHotRoute
  '/kham-pha-ngau-nhien': typeof KhamPhaNgauNhienRoute
  '/truyen-thuyet': typeof TruyenThuyetRouteWithChildren
  '/ve-chung-toi': typeof VeChungToiRoute
  '/truyen-thuyet/$slug': typeof TruyenThuyetSlugRoute
  '/truyen-thuyet/': typeof TruyenThuyetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dang-hot': typeof DangHotRoute
  '/kham-pha-ngau-nhien': typeof KhamPhaNgauNhienRoute
  '/ve-chung-toi': typeof VeChungToiRoute
  '/truyen-thuyet/$slug': typeof TruyenThuyetSlugRoute
  '/truyen-thuyet': typeof TruyenThuyetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dang-hot': typeof DangHotRoute
  '/kham-pha-ngau-nhien': typeof KhamPhaNgauNhienRoute
  '/truyen-thuyet': typeof TruyenThuyetRouteWithChildren
  '/ve-chung-toi': typeof VeChungToiRoute
  '/truyen-thuyet/$slug': typeof TruyenThuyetSlugRoute
  '/truyen-thuyet/': typeof TruyenThuyetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dang-hot'
    | '/kham-pha-ngau-nhien'
    | '/truyen-thuyet'
    | '/ve-chung-toi'
    | '/truyen-thuyet/$slug'
    | '/truyen-thuyet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dang-hot'
    | '/kham-pha-ngau-nhien'
    | '/ve-chung-toi'
    | '/truyen-thuyet/$slug'
    | '/truyen-thuyet'
  id:
    | '__root__'
    | '/'
    | '/dang-hot'
    | '/kham-pha-ngau-nhien'
    | '/truyen-thuyet'
    | '/ve-chung-toi'
    | '/truyen-thuyet/$slug'
    | '/truyen-thuyet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DangHotRoute: typeof DangHotRoute
  KhamPhaNgauNhienRoute: typeof KhamPhaNgauNhienRoute
  TruyenThuyetRoute: typeof TruyenThuyetRouteWithChildren
  VeChungToiRoute: typeof VeChungToiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-hot': {
      id: '/dang-hot'
      path: '/dang-hot'
      fullPath: '/dang-hot'
      preLoaderRoute: typeof DangHotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kham-pha-ngau-nhien': {
      id: '/kham-pha-ngau-nhien'
      path: '/kham-pha-ngau-nhien'
      fullPath: '/kham-pha-ngau-nhien'
      preLoaderRoute: typeof KhamPhaNgauNhienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen-thuyet': {
      id: '/truyen-thuyet'
      path: '/truyen-thuyet'
      fullPath: '/truyen-thuyet'
      preLoaderRoute: typeof TruyenThuyetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ve-chung-toi': {
      id: '/ve-chung-toi'
      path: '/ve-chung-toi'
      fullPath: '/ve-chung-toi'
      preLoaderRoute: typeof VeChungToiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen-thuyet/': {
      id: '/truyen-thuyet/'
      path: '/'
      fullPath: '/truyen-thuyet/'
      preLoaderRoute: typeof TruyenThuyetIndexRouteImport
      parentRoute: typeof TruyenThuyetRoute
    }
    '/truyen-thuyet/$slug': {
      id: '/truyen-thuyet/$slug'
      path: '/$slug'
      fullPath: '/truyen-thuyet/$slug'
      preLoaderRoute: typeof TruyenThuyetSlugRouteImport
      parentRoute: typeof TruyenThuyetRoute
    }
  }
}

interface TruyenThuyetRouteChildren {
  TruyenThuyetSlugRoute: typeof TruyenThuyetSlugRoute
  TruyenThuyetIndexRoute: typeof TruyenThuyetIndexRoute
}

const TruyenThuyetRouteChildren: TruyenThuyetRouteChildren = {
  TruyenThuyetSlugRoute: TruyenThuyetSlugRoute,
  TruyenThuyetIndexRoute: TruyenThuyetIndexRoute,
}

const TruyenThuyetRouteWithChildren = TruyenThuyetRoute._addFileChildren(
  TruyenThuyetRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DangHotRoute: DangHotRoute,
  KhamPhaNgauNhienRoute: KhamPhaNgauNhienRoute,
  TruyenThuyetRoute: TruyenThuyetRouteWithChildren,
  VeChungToiRoute: VeChungToiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
